import Head from 'next/head'
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
import About from '../components/About'
import Skills from '../components/Skills'
import Work from '../components/Work'
import Contact from '../components/Contact'
import Footer from '../components/Footer'
import { sanityClient } from '../lib/sanity'

const worksQuery = `
  *[_type == "works"]{
    _id,
    slug,
    title,
    imgUrl,
    tag
  }
`


export default function Home({works}) {
  return (
    <div>
      <Head>
        <title>Akshay Agarwal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main>
        <Hero />
        <About />
        <Skills />
        <Work works={works}/>
        <Contact />
      </main>
      <Footer />

    </div>
  )
}

export async function getStaticProps() {
  const works = await sanityClient.fetch(worksQuery)
  return {
    props: {
      works
    }
  }
}
