import Head from 'next/head'
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
import About from '../components/About'
import Skills from '../components/Skills'
import Work from '../components/Work'
import Contact from '../components/Contact'
import Footer from '../components/Footer'
import { sanityClient } from '../lib/sanity'
import { Toaster } from 'react-hot-toast'
import TawkMessengerReact from '@tawk.to/tawk-messenger-react';
import { useRef } from 'react';

const worksQuery = `
  *[_type == "works"]{
    _id,
    slug,
    title,
    imgUrl,
    tag
  }
`


export default function Home({works}) {

  

  return (
    <div>
      <Head>
        <title>Akshay Agarwal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="google-site-verification" content="tvvlUuK3pj5nwuR16UVdwYLBOhwJiUnytPL30QzLasI" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toaster />
      <Navbar />
      <main className="relative">
        <div>
          <TawkMessengerReact
            propertyId="629fa1ecb0d10b6f3e762e26"
            widgetId="1g4vp117k"
          />
        </div>
        <Hero />
        <About />
        <Skills />
        <Work works={works}/>
        <Contact />
      </main>
      <Footer />

    </div>
  )
}

export async function getStaticProps() {
  const works = await sanityClient.fetch(worksQuery)
  return {
    props: {
      works
    }
  }
}
